/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    borderRadius: {
      '3xs': 'var(--radius-3xs)',
      '2xs': 'var(--radius-2xs)',
      'xs': 'var(--radius-xs)',
      's': 'var(--radius-s)',
      'm': 'var(--radius-m)',
      'l': 'var(--radius-l)',
      'xl': 'var(--radius-xl)',
      '2xl': 'var(--radius-2xl)',
      '3xl': 'var(--radius-3xl)',
      '4xl': 'var(--radius-4xl)',
      'full': 'var(--radius-full)',
    },
    fontSize: {
      table_cell: ['0.75rem', {
        lineHeight: '0.9rem',
        letterSpacing: '0.0875rem',
        fontWeight: '400',
      }],
      table_header: ['0.875rem', {
        lineHeight:"1.05rem",
        letterSpacing:"0.0938rem",
        fontWeight:"700",
      }],
      table_number: ['1rem', {
        lineHeight:"1.2rem",
        letterSpacing:"0.1rem",
        fontWeight:"400",
      }],
      body_small: ['0.875rem', {
        letterSpacing:"0.1rem",
        lineHeight:"1.05rem",
        fontWeight:"400",
      }],
      body_regular: ['1rem', {
        letterSpacing:"0.1rem",
        lineHeight:"1.2rem",
        fontWeight:"400",
      }],
      body_large: ['1.125rem', {
        letterSpacing:"0.0938rem",
        lineHeight:"1.4063rem",
        fontWeight:"400",
      }],
      subtitle: ['1.5rem', {
        letterSpacing:"0.0875rem",
        lineHeight:"1.8rem",
        fontWeight:"400",
      }],
      title: ['2rem', {
        letterSpacing:"0.0812rem",
        lineHeight:"2.4rem",
        fontWeight:"700",
      }],
      h6: ['1.25rem', {
        letterSpacing:"0.0938rem",
        lineHeight:"1.5rem",
        fontWeight:"400",
      }],
      h5: ['1.5625rem', {
        letterSpacing:"0.0938rem",
        lineHeight:"1.875rem",
        fontWeight:"400",
      }],
      h4: ['1.9375rem', {
        letterSpacing:"0.0875rem",
        lineHeight:"2.325rem",
        fontWeight:"700",
      }],
      h3: ['2.4375rem', {
        letterSpacing:"0.0875rem",
        lineHeight:"2.925rem",
        fontWeight:"700",
      }],
      h2: ['3.0625rem', {
        letterSpacing:"0.0812rem",
        lineHeight:"3.675rem",
        fontWeight:"700",
      }],
      h2: ['3.8125rem', {
        letterSpacing:"0.075rem",
        lineHeight:"4.575rem",
        fontWeight:"700",
      }],
      btn_small: ['0.875rem', {
        fontWeight:"700",
        lineHeight:"1.0625rem",
      }],
      btn_medium: ['1rem', {
        fontWeight:"700",
        lineHeight:"1.25rem",
      }],
      btn_large: ['1.125rem', {
        fontWeight:"700",
        lineHeight:"1.4375rem",
      }],
      caption: ['0.75rem', {
        fontWeight:"400",
        letterSpacing:"0.0875rem",
        lineHeight:"0.9rem"
      }],
      small_text: ['0.75rem', {
        fontWeight:"400",
        letterSpacing:"0.0812rem",
        lineHeight:"0.9rem"
      }],
      footnote: ['0.625rem', {
        fontWeight:"400",
        letterSpacing:"0.075rem",
        lineHeight:"0.75rem"
      }],
    },
    screens:{
      'sm': '640px',
      'md': '768px',
      'lg': '1024px',
      'xl': '1440px',
      '2xl': '1536px',
    },
    extend: {
      boxShadow: {
        'low': '0 1px 3px 0 rgba(0 0 0 / 0.2)',
      },
      colors: {
        surface: {
          container_low: ' var(--gray-gray-50)',
          container_default: 'var(--gray-gray-100)',
          container_high: 'var(--gray-gray-200)',
          border_low: 'var(--gray-gray-300)',
          border_default: 'var(--gray-gray-400)',
          border_high: 'var(--gray-gray-700)',
          border_highest: 'var(--gray-gray-800)',
          text_lowest: 'var(--gray-gray-500)',
          text_default: 'var(--gray-gray-800)',
          text_low: 'var(--gray-gray-600)',
          text_high: 'var(--gray-gray-900)',
          text_disabled: 'var(--gray-gray-400)',
          inverse_container_low: 'var(--gray-gray-700)',
          inverse_container_default: 'var(--gray-gray-800)',
          inverse_container_high: 'var(--gray-gray-900)',
          inverse_container_highest: 'var(--gray-gray-950)',
          inverse_text_lowest: 'var(--gray-gray-300)',
          inverse_text_low: 'var(--gray-gray-200)',
          inverse_text_default: 'var(--gray-gray-100)',
          inverse_text_high: ' var(--gray-gray-50)',
        },
        primary: {
          container_lowest: 'var(--purple-purple-300)',
          container_low: 'var(--purple-purple-400)',
          container_default: 'var(--purple-purple-500)',
          container_high: 'var(--purple-purple-700)',
          container_disabled: 'var(--purple-purple-200)',
          border_low: 'var(--purple-purple-300)',
          border_lowest: 'var(--purple-purple-100)',
          border_default: 'var(--purple-purple-500)',
          border_high: 'var(--purple-purple-700)',
          border_highest: 'var(--purple-purple-900)',
          text_lowest: 'var(--purple-purple-200)',
          text_low: 'var(--purple-purple-300)',
          text_default: 'var(--purple-purple-500)',
          text_high: 'var(--purple-purple-700)',
        },
        error: {
          container_low: 'var(--red-red-400)',
          container_default: 'var(--red-red-500)',
          container_high: 'var(--red-red-700)',
          border_lowest: 'var(--red-red-100)',
          border_low: 'var(--red-red-300)',
          border_default: 'var(--red-red-500)',
          border_high: 'var(--red-red-700)',
          text_lowest: 'var(--red-red-200)',
          text_low: 'var(--red-red-300)',
          text_default: 'var(--red-red-500)',
          text_high: 'var(--red-red-700)',
          inverse_container_low: 'var(--red-red-200)',
          inverse_container_default: 'var(--red-red-300)',
          inverse_container_high: 'var(--red-red-400)',
        },
        success: {
          container_low: 'var(--green-green-600)',
          container_default: 'var(--green-green-700)',
          container_high: 'var(--green-green-800)',
          inverse_container_low: 'var(--green-green-300)',
          inverse_container_default: 'var(--green-green-400)',
          inverse_container_high: 'var(--green-green-500)',
          text_lowest: 'var(--green-green-300)',
          text_low: 'var(--green-green-400)',
          text_default: 'var(--green-green-600)',
          text_high: 'var(--green-green-700)',
          border_low: 'var(--green-green-300)',
          border_lowest: 'var(--green-green-100)',
          border_default: 'var(--green-green-500)',
          border_high: 'var(--green-green-700)',
        },
        warning: {
          container_low: 'var(--orange-orange-400)',
          container_default: 'var(--orange-orange-500)',
          container_high: 'var(--orange-orange-600)',
          inverse_container_low: 'var(--orange-orange-100)',
          inverse_container_default: 'var(--orange-orange-200)',
          inverse_container_high: 'var(--orange-orange-300)',
          text_lowest: 'var(--orange-orange-200)',
          text_low: 'var(--orange-orange-300)',
          text_default: 'var(--orange-orange-500)',
          text_high: 'var(--orange-orange-600)',
          border_low: 'var(--orange-orange-300)',
          border_lowest: 'var(--orange-orange-100)',
          border_default: 'var(--orange-orange-500)',
          border_high: 'var(--orange-orange-700)',
        },
        info: {
          container_low: 'var(--blue-blue-400)',
          container_default: 'var(--blue-blue-500)',
          container_high: 'var(--blue-blue-600)',
          inverse_container_low: 'var(--blue-blue-100)',
          inverse_container_default: 'var(--blue-blue-200)',
          inverse_container_high: 'var(--blue-blue-300)',
          text_lowest: 'var(--blue-blue-200)',
          text_low: 'var(--blue-blue-300)',
          text_default: 'var(--blue-blue-500)',
          text_high: 'var(--blue-blue-600)',
          border_lowest: 'var(--blue-blue-100)',
          border_low: 'var(--blue-blue-300)',
          border_default: 'var(--blue-blue-500)',
          border_high: 'var(--blue-blue-700)',
        }
      },
    },
  },
  plugins: [],
};